# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: shabashkinoleg 
google_analytics: 
title: Oleg Shabashkin

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Blog

description: My notes so as not to forget the useful development.
author:
  name: Shabashkin Oleg
  email: shabashkin93@gmail.com
  github: Shabashkin93
  twitter:
  telegram: Shabashkin93
  vk: parkour23
  linkedin: 
  bio: 
  email_md5: f3aeb4701012008c54f2cf909a2bb722

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
  - jekyll-sitemap